#!/bin/bash
###########################################################
# Script checks StorCLI for non-optimal virtual disks and
# for physical disks that are either offline or bad
#
# On any state deviation, an email notification will be
# sent to the root user of the server.
###########################################################

ALLOWED_VD_STATES=(optl)
ALLOWED_PD_STATES=(onln ugood ghs dhs)

# Possible names of StorCLI binary
STORCLI_BINARIES=( "storcli64" "storcli" )
# If StorCLI binary is not found in path, try these locations also
EXTRA_SEARCH_PATHS=( "/opt/MegaRAID/storcli/" "/usr/local/sbin/" "/usr/local/bin/" )

# StorCLI path
locate_storcli() {
    for BIN in "${STORCLI_BINARIES[@]}"; do
        STORCLI=$( which $BIN )
        FOUND_SCLI=$?
        if [[ $FOUND_SCLI -ne 0 ]]; then
            for EXTRA in "${EXTRA_SEARCH_PATHS[@]}"; do
                if [[ -f "$EXTRA$BIN" && -x "$EXTRA$BIN" ]]; then
                    STORCLI="$EXTRA$BIN"
                    break 2
                fi
            done
        else
            break
        fi
    done
    echo "$STORCLI"
}

STORCLI_PATH=$( locate_storcli )
if [[ -z $STORCLI_PATH ]]; then
    echo "ERROR: Could not find StorCLI binary!"
    exit 1
fi

# Show all virtual disks on all controllers
# storcli64 /call/vall show

# Show all physical disks on all controllers
# storcli64 /call/eall/sall show

