#!/bin/bash
###########################################################
# Quick script to silence a RAID card sounding the alarm
###########################################################

# Default to controller 0
CID=${1:-0}
# Only allow controller id to be 0 through 9
if [[ ! $CID =~ ^[0-9]$ ]]; then
    echo "ERROR: Controller number out of bounds."
    exit 1
fi

# Possible names of StorCLI binary
STORCLI_BINARIES=( "storcli64" "storcli" "perccli64" "perccli" )
# If StorCLI binary is not found in path, try these locations also
EXTRA_SEARCH_PATHS=( "/opt/MegaRAID/storcli/" "/usr/local/sbin/" "/usr/local/bin/" "/opt/MegaRAID/perccli/" )

# StorCLI path
locate_storcli() {
    for BIN in "${STORCLI_BINARIES[@]}"; do
        STORCLI=$( which $BIN )
        FOUND_SCLI=$?
        if [[ $FOUND_SCLI -ne 0 ]]; then
            for EXTRA in "${EXTRA_SEARCH_PATHS[@]}"; do
                if [[ -f "$EXTRA$BIN" && -x "$EXTRA$BIN" ]]; then
                    STORCLI="$EXTRA$BIN"
                    break 2
                fi
            done
        else
            break
        fi
    done
    echo "$STORCLI"
}

STORCLI_PATH=$( locate_storcli )
if [[ -z $STORCLI_PATH ]]; then
    echo "ERROR: Could not find StorCLI binary!"
    exit 1
fi

$STORCLI_PATH /c$CID set alarm=silence

